<!DOCTYPE html>
<html>
    <head>
        <title>Imagenes</title>
        <meta lang="es" charset="utf-8"> 
        <base href="<?php echo URL_BASE ?>">
        <script type="text/javascript" src="<?php echo $this->rutaPublico ?>js/jquery-1.8.2.js"></script>
        <script type="text/javascript" src="<?php echo $this->rutaPublico ?>js/tinymce/jscripts/tiny_mce/tiny_mce_popup.js"></script>
        <script type="text/javascript" src="<?php echo $this->rutaPublico ?>js/tinymce/jscripts/tiny_mce/plugins/imgphp/js/dialog.js"></script>
        <link rel="stylesheet" href="<?php echo $this->rutaPublico ?>css/pop_up.css" media="all" type="text/css">
        <script type="text/javascript">
            $(function() {
                $('.opt_img').click(function(e) {
                    e.preventDefault();
                    $('#usar_img').val($(this).attr('href') + '" alt="' + $(this).attr('title'));
                    $('form').submit();
                })
            })
        </script>
    </head>
    <body>
        <h1>Gestor de Imágenes - KintuCms</h1>
        <form onsubmit="ImgphpDialog.insert(); return false;" action="#">
            <article>
                <p>
                    <a class="add" href="<?php echo URL_BASE; ?>archivo/img_nuevo">Subir Imagen</a>
                </p>
                <p>Elija una imagen de la lista</p>  
                <?php if (Sesion::get('msj')) : ?>
                    <div class="correcto">
                        <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/correcto.png"> 
                        <?php
                        echo Sesion::get('msj');
                        Sesion::set('msj', '');
                        ?>
                    </div>
                <?php endif; ?>
                <?php if ($this->datos) : ?>
                    <table class="table">
                        <tr>
                            <th>vista previa</th><th colspan="3">operaciones</th>               
                        </tr>
                        <?php for ($i = 0; $i < count($this->datos); $i++) : ?>
                            <tr>                
                                <td><img alt="<?php echo $this->datos[$i]['descripcion']; ?>" src="<?php echo URL_BASE, 'publico/img/articulos/', $this->datos[$i]['nombre']; ?>"></td>
                                <td>
                                    <a href="<?php echo URL_BASE, 'archivo/img_ver/', $this->datos[$i]['nombre']; ?>">Ver original</a>
                                </td>
                                <td><a class="opt_img" title="<?php echo $this->datos[$i]['descripcion'] ?>" href="<?php echo URL_BASE, 'publico/img/articulos/', $this->datos[$i]['nombre']; ?>">Usar</a></td>
                                <td><a href="<?php echo URL_BASE, 'archivo/img_eliminar/', $this->datos[$i]['id']; ?>">Eliminar</a></td>
                            </tr>
                        <?php endfor; ?>
                    </table>
                    <?php require RAIZ . SD . 'vistas' . SD . '_utilidades' . SD . 'paginador.phtml'; ?>
                <?php else : ?>
                    <p>No se encontró resultados.</p>
                <?php endif; ?> 
            </article>
            <input id="usar_img" name="usar_img" type="hidden" class="text">
        </form>
    </body>
</html>