<article>
    <form method="post" action="" class="form" enctype="multipart/form-data">
        <h1><?php echo $this->titulo; ?></h1>
        <p>¿Desea eliminar la imagen &Lt; <?php echo $this->datos['descripcion']; ?> &Gt;?</p>
        <?php if (isset($this->error)) : ?>
            <div class="error">
                <img alt="img" src="<?php echo $this->plantilla; ?>img/error.png">
                <span>Se ha detectado los siguientes errores:</span>
                <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                    <?php echo '<br>', $i + 1, '. ', $this->error[$i]; ?>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
        <input type="hidden" name="guardar" value="1">
        <ul>                          
            <li>
                <input type="submit" class="submit" value="Confirmar"> <a href="<?php echo URL_BASE, 'slider/listar', ADMIN ?>">Cancelar</a>
            </li>
        </ul> 
    </form>
</article>