<article>
    <h1>Módulo slider</h1>
    <p>Este módulo le permite administrar el slider.</p>
    <ul class="ul_index">
        <li>
            <h4><a href="<?php echo URL_BASE, 'slider/nuevo', ADMIN ?>">Nueva imagen</a></h4>
            <p>Esta opción le permite agregar una nueva imagen al slider.</p>
        </li>
        <li>
            <h4><a href="<?php echo URL_BASE, 'slider/listar', ADMIN ?>">Listar imagenes</a></h4>
            <p>Esta opción le permite listar las imagenes del slider.</p>
        </li>
    </ul>
</article>