<article>
    <h1><?php echo $this->titulo ?></h1>  
    <p>
        El módulo widget le permite la administración de widgets. Un widget es una
        porcion de contenido que se muestra en las posiciones de tu plantilla.
    </p>
    <ul class="submenu">
        <?php $subm = $this->submenu['submenu']; ?>
        <?php for ($i = 0; $i < count($subm); $i++): ?>
            <li>
                <h3><a href="<?php echo URL_BASE, $subm[$i]['url'], ADMIN ?>"><?php echo $subm[$i]['texto']; ?></a></h3>
                <p><?php echo $subm[$i]['detalle']; ?></p>
            </li>
        <?php endfor; ?>
    </ul>
</article>