<article>                   
    <form method="post" action="" class="form">
        <h1><?php echo $this->titulo ?></h1>
        <input type="hidden" name="guardar" value="1">
        <ul>              
            <li>
                <input type="submit" class="submit" value="Confirmar"><a class="atras" href="<?php echo URL_BASE, 'plantilla/listar', ADMIN ?>">Cancelar</a>
            </li>
        </ul>    
    </form>
</article>