<article>                   
    <form method="post" action="" class="form">
        <h1><?php echo $this->titulo; ?></h1>
        <?php if (isset($this->error)) : ?>
            <div class="error">
                <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/error.png">
                <span>Se ha detectado los siguientes errores:</span>
                <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                    <?php echo '<br>', $i + 1, '. ', $this->error[$i]; ?>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
        <input type="hidden" name="guardar" value="1">
        <ul>              
            <li>
                <label for="nombre">Nombre completo:</label>
                <input type="text" id="nombre" name="nombre" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['nombre'])) echo $this->datos['nombre']; ?>"
                       pattern="^[a-zñáéíóú ]{15,}$" title="Utiliza solo letras, 15 caracteres como mínimo">
            </li>
            <li>
                <label for="login">Login:</label>
                <input type="text" id="login" name="login" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['login'])) echo $this->datos['login']; ?>"
                       pattern="^[a-z0-9_\-]{6,}$" title="Utiliza sólo letras (a-z), guíon, subguión y números, 6 caracteres como mínimo">
            </li>                    
            <li>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['email'])) echo $this->datos['email']; ?>"
                       pattern="^[a-z0-9_\-\.]+@[a-z0-9_\-\.]+\.[a-z]{2,4}$" title="Escribe tu email">
            </li>                    
            <li>
                <label for="pass">Contraseña:</label>
                <input type="password" id="pass" name="pass" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['pass'])) echo $this->datos['pass']; ?>"
                       pattern="^.{6,}" title="Utiliza 6 caracteres como mínimo, las contraseñas cortas son fáciles de adivinar">
            </li>
            <li>
                <label for="repass">Repite contraseña:</label>
                <input type="password" id="repass" name="repass" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['repass'])) echo $this->datos['repass']; ?>"
                       pattern="^.{6,}" title="Utiliza 6 caracteres como mínimo, las contraseñas cortas son fáciles de adivinar">
            </li>
            <li>
                <label for="rol">Rol:</label>
                <select id="rol" name="rol" required>
                    <option value="">Seleccione</option>
                    <?php for ($i = 0; $i < count($this->rol); $i++) : ?>
                        <option value="<?php echo $this->rol[$i]['id']; ?>"<?php if (isset($this->datos['rol']) && $this->datos['rol'] == $this->rol[$i]['id']) echo ' selected'; ?>>
                            <?php echo $this->rol[$i]['rol']; ?>
                        </option>
                    <?php endfor; ?>
                </select>
            </li>
            <li>
                <input type="submit" class="submit" value="Guardar">
            </li>
        </ul> 
    </form>
</article>