<article>                   
    <form method="post" action="" class="form" enctype="multipart/form-data">
        <h1><?php echo $this->titulo ?></h1>
        <?php if (isset($this->error)) : ?>
            <div class="error">
                <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/error.png">
                <span>Se ha detectado los siguientes errores:</span>
                <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                    <?php echo '<br>', $i + 1, '. ', $this->error[$i]; ?>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
        <input type="hidden" name="guardar" value="1">
        <ul>
            <li>                    
                <label for="foto">Nueva imagen:</label>
                <input type="file" id="foto" name="foto" class="in" accept="image/jpeg,image/png,image/gif" required>
            </li> 
            <li>
                <input type="submit" class="submit" value="Guardar"><a href="<?php echo URL_BASE, 'cuenta', ADMIN ?>">Cancelar</a>
            </li>
        </ul> 
    </form>
</article>