<article>                   
    <form method="post" action="" class="form">
        <h1><?php echo $this->titulo; ?></h1>
        <?php if (isset($this->error)) : ?>
            <div class="error">
                <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/error.png">
                <span>Se ha detectado los siguientes errores:</span>
                <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                    <?php echo '<br>', $i + 1, '. ', $this->error[$i]; ?>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
        <input type="hidden" name="guardar" value="1">
        <ul>
            <li>
                <label for="nombre">Nombre completo:</label>
                <input type="text" id="nombre" name="nombre" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['nombre'])) echo $this->datos['nombre']; ?>"
                       pattern="^[a-zñáéíóú ]{15,}$" title="Utiliza solo letras, 15 caracteres como mínimo">
            </li>
            <li>
                <label for="login">Login:</label>
                <input type="text" id="login" name="login" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['login'])) echo $this->datos['login']; ?>"
                       pattern="^[a-z0-9_\-]{6,}$" title="Utiliza sólo letras (a-z), guion, subguión y números, 6 caracteres como mínimo">
            </li>                    
            <li>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['email'])) echo $this->datos['email']; ?>"
                       pattern="^[a-z0-9_\-\.]+@[a-z0-9_\-\.]+\.[a-z]{2,4}$" title="Escribe tu email">
            </li>                    
            <li>
                <label for="acerca">Acerca de mí:</label>
                <textarea id="acerca" name="acerca" required rows="2"><?php if (isset($this->datos['acerca'])) echo $this->datos['acerca']; ?></textarea>
            </li>
            <li>
                <input type="submit" class="submit" value="Guardar"><a class="atras" href="<?php echo URL_BASE, 'cuenta', ADMIN ?>">Cancelar</a>
            </li>
        </ul> 
    </form>
</article>