<article>                   
    <form method="post" action="" class="form">
        <h1><?php echo $this->titulo ?></h1>
        <?php if (isset($this->error)) : ?>
            <div class="error">
                <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/error.png">
                <span>Se ha detectado los siguientes errores:</span>
                <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                    <?php echo '<br>', $i + 1, '. ', $this->error[$i]; ?>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
        <input type="hidden" name="guardar" value="1">
        <ul>
            <li>
                <label for="pass">Contraseña actual:</label>
                <input type="password" id="pass" name="pass" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['pass'])) echo $this->datos['pass']; ?>"
                       pattern="^.{6,}" title="Utiliza 6 caracteres como mínimo, las contraseñas cortas son fáciles de adivinar">
            </li>
            <li>
                <label for="new-pass">Nueva contraseña:</label>
                <input type="password" id="new-pass" name="new-pass" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['new-pass'])) echo $this->datos['new-pass']; ?>"
                       pattern="^.{6,}" title="Utiliza 6 caracteres como mínimo, las contraseñas cortas son fáciles de adivinar">
            </li>
            <li>
                <label for="re-pass">Repite nueva contraseña:</label>
                <input type="password" id="re-pass" name="re-pass" class="in" placeholder="Requerido" required
                       value="<?php if (isset($this->datos['re-pass'])) echo $this->datos['re-pass']; ?>"
                       pattern="^.{6,}" title="Utiliza 6 caracteres como mínimo, las contraseñas cortas son fáciles de adivinar">
            </li>
            <li>
                <input type="submit" class="submit" value="Guardar"><a class="atras" href="<?php echo URL_BASE, 'cuenta', ADMIN ?>">Cancelar</a>
            </li>
        </ul> 
    </form>
</article>