<article>
    <h1><?php echo $this->titulo; ?></h1>
    <p>
        El módulo comentario le permite la administración de los comentarios.
    </p>
    <ul class="submenu">
        <?php $subm = $this->submenu['submenu']; ?>
        <?php for ($i = 0; $i < count($subm); $i++): ?>
            <li>
                <h3><a href="#"><?php echo $subm[$i]['texto']; ?></a></h3>
                <p><?php echo $subm[$i]['detalle']; ?></p>
            </li>
        <?php endfor; ?>
    </ul>
</article>