<article>
    <h1>Configuración de Sitio</h1>
    <p>Este módulo le permite administrar los parámetros de su Sitio.</p>
    <ul class="ul_index">
        <li>
            <h4><a href="<?php echo URL_BASE, 'config/principal', ADMIN ?>">Pagina de Inicio</a></h4>
            <p>Esta opción le permite ver y elegir la página de inicio.</p>
        </li>
        <li>
            <h4><a href="<?php echo URL_BASE, 'config/ver', ADMIN ?>">Ver Configuración</a></h4>
            <p>Esta opción le permite ver parámetros de su Sitio.</p>
        </li>
        <li>
            <h4><a href="<?php echo URL_BASE, 'config/editar', ADMIN ?>">Editar Configuración</a></h4>
            <p>Esta opción le permite editar parámetros de su Sitio.</p>
        </li>
    </ul>
</article>