<article>
    <h1><?php echo $this->titulo ?></h1> 
    <p><a class="atras" href="<?php echo URL_BASE, 'config/editar', ADMIN ?>">Editar Parámetros</a> | <a class="atras" href="<?php echo URL_BASE, 'config', ADMIN ?>">Regresar</a></p>
    <?php if (Sesion::get('msj')) : ?>
        <div class="correcto">
            <img alt="img" src="<?php echo $this->rutaPublico ?>img/app/correcto.png"> 
            <?php
            echo Sesion::get('msj');
            Sesion::set('msj', '');
            ?>
        </div>
    <?php endif; ?>
    <table class="table">
        <tr>
            <th>Parámetro</th><th>valor</th><th>detalle</th>                 
        </tr>
        <?php for ($i = 0; $i < 6; $i++) : ?>
            <tr>
                <td><?php echo $this->datos[$i]['parametro']; ?></td>
                <td><?php echo $this->datos[$i]['valor']; ?></td>
                <td><?php echo $this->datos[$i]['detalle']; ?></td>
            </tr>
        <?php endfor; ?>
    </table>
    <p>Algunos datos no se muestran por seguridad.</p>
</article>