<h2>Elija una opción</h2>
<ul>
    <li><a href="menu/articulos" class="elegirUrl">Enlace a un artículo</a></li>
    <li><a href="articulo/reciente/1" class="click">Enlace a lista de artículos recientes</a></li>
    <li><a href="menu/categorias" class="elegirUrl">Enlace a lista de artículos de una categoría</a></li>
    <li><a href="articulo/categorias/1" class="click">Enlace a lista categorías</a></li>
</ul>
<p>Click fuera del cuadro blanco para salir</p>